name: Download Latest Stocks

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: install-dependencies  
        run: pip install -r requirements.txt

      # Fetch stock data using Alpha Vantage
      - name: fetch-stocks-by-exchange
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: python script/fetch_tickers_by_exchange.py
      - name: commit-new-files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
